### PR TITLE
Show /ep downgrade only if DefaultType is EXILE

### PR DESCRIPTION
**Pull request by drekamor**
The message confuses many players and is not needed as there's no exile pearls on CivMC.

### CODE REVIEW

**Comment by wingzero54** [comment]
Makes sense to me, anybody opposed or have an issue with this?

**Comment by drekamor** [comment]
Oh hell, let me fix this rq

**Comment by Diet-Cola** [comment]
Wouldnt this leave a weird thing with all existing pearls having this lore and new ones not having the lore?

**Comment by Diet-Cola** [comment]
Otherwise makes sense for sure

**Comment by drekamor** [comment]
> Wouldnt this leave a weird thing with all existing pearls having this lore and new ones not having the lore?

I don't know much about civ plugins code at all, just started working with them. But it seemed for me that the lore is generated every time the pearl is taken or, at least, every time it's health changes

**Comment by Diet-Cola** [comment]
Gonna throw this on test shortly

**Comment by Diet-Cola** [comment]
Seems to look ok 
image

**Comment by drekamor** [comment]
Pearled SoundTech? Admin war on CivMC has just began :)

**Review by wingzero54 — APPROVED** [review]
Good update, thank you

**Pull request merged**
